import { ImgHTMLAttributes, useMemo, useState, useEffect, type SyntheticEvent } from 'react';
import { 
  extractAltText, 
  generateResponsiveSrcSet, 
  generateSizesAttribute,
  isUploadedImage 
} from '@/lib/image-utils';

const FALLBACK_PLACEHOLDER = '/attached_assets/generated_images/Blog_placeholder_image_201b6785.png';

interface SmartImageProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'alt' | 'sizes'> {
  src: string;
  alt?: string; // Optional - will be auto-generated from filename if not provided
  title?: string; // Optional - used as alt if provided, otherwise auto-generated
  priority?: boolean; // Custom prop for eager loading (not passed to img tag)
  disableResponsive?: boolean; // Disable automatic responsive images
  sizes?: string; // Custom sizes attribute for responsive images
  disableFallback?: boolean; // Disable fallback placeholder (for branch icons, university logos, etc.)
}

/**
 * Smart Image Component
 * Automatically detects and assigns alt text from filename or title if not provided
 * Serves images as WebP format for better performance
 * Automatically generates responsive srcset for mobile and desktop optimization
 * 
 * Features:
 * - Auto-generated alt text from filename
 * - Smart responsive srcset (only for uploaded images with pre-generated variants)
 * - Backwards compatible with legacy images (no 404s)
 * - Optimal image selection based on screen size
 * 
 * Priority order for alt text:
 * 1. Explicitly provided alt prop
 * 2. Title prop (if provided)
 * 3. Auto-generated from filename
 * 
 * @example
 * // Auto-responsive image with auto-generated alt
 * <SmartImage src="/api/uploads/best-study-abroad-consultants_123456.webp" />
 * // Browser automatically selects: 320w on mobile, 640w on tablet, 1280w on desktop
 * 
 * @example
 * // Priority image (LCP candidate)
 * <SmartImage src="/api/uploads/hero.webp" priority />
 * 
 * @example
 * // Disable responsive for specific use case
 * <SmartImage src="/api/uploads/logo.webp" disableResponsive />
 */
export function SmartImage({ 
  src, 
  alt, 
  title, 
  priority, 
  disableResponsive, 
  sizes: customSizes,
  disableFallback = false,
  onError: consumerOnError,
  ...props 
}: SmartImageProps) {
  const [imgSrc, setImgSrc] = useState(src);
  const [hasError, setHasError] = useState(false);
  
  // Reset error state when src prop changes
  useEffect(() => {
    setImgSrc(src);
    setHasError(false);
  }, [src]);
  
  // Priority: alt prop > title prop > auto-generated from filename
  const autoGeneratedAlt = extractAltText(src);
  const finalAlt = alt || title || autoGeneratedAlt;
  
  // Use title if provided, otherwise use the auto-generated alt as title
  const finalTitle = title || autoGeneratedAlt;
  
  // Generate responsive srcset for uploaded images only
  const { srcSet, sizes } = useMemo(() => {
    if (disableResponsive || !src || hasError) {
      return { srcSet: undefined, sizes: undefined };
    }
    
    // Only generate srcset for uploaded images (not attached_assets)
    // This avoids 404 errors on legacy images without pre-generated variants
    if (!isUploadedImage(src)) {
      return { srcSet: undefined, sizes: undefined };
    }
    
    // Generate srcset with multiple sizes
    const srcSet = generateResponsiveSrcSet(src);
    
    // Generate sizes attribute for optimal selection
    const sizes = generateSizesAttribute(customSizes);
    
    return { srcSet, sizes };
  }, [src, disableResponsive, customSizes, hasError]);
  
  const handleError = (e: SyntheticEvent<HTMLImageElement, Event>) => {
    // Only use fallback if not disabled (for blogs/events only)
    if (!disableFallback && !hasError && imgSrc !== FALLBACK_PLACEHOLDER) {
      setHasError(true);
      setImgSrc(FALLBACK_PLACEHOLDER);
    }
    consumerOnError?.(e);
  };
  
  return (
    <img
      src={imgSrc}
      srcSet={hasError ? undefined : srcSet}
      sizes={hasError ? undefined : sizes}
      alt={finalAlt}
      title={finalTitle}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      onError={handleError}
      {...(priority ? { fetchpriority: "high" } : {})}
      {...props}
    />
  );
}

export default SmartImage;
