import { ImgHTMLAttributes, useMemo } from 'react';
import { extractAltText } from '@/lib/image-utils';

interface SmartImageProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'alt'> {
  src: string;
  alt?: string; // Optional - will be auto-generated from filename if not provided
  title?: string; // Optional - used as alt if provided, otherwise auto-generated
  priority?: boolean; // Custom prop for eager loading (not passed to img tag)
  disableResponsive?: boolean; // Disable automatic responsive images
}

/**
 * Smart Image Component
 * Automatically detects and assigns alt text from filename or title if not provided
 * Serves images as WebP format for better performance
 * Automatically generates responsive srcset for mobile optimization
 * 
 * Priority order for alt text:
 * 1. Explicitly provided alt prop
 * 2. Title prop (if provided)
 * 3. Auto-generated from filename
 * 
 * @example
 * // Alt text auto-generated from filename
 * <SmartImage src="/api/uploads/best-study-abroad-consultants_123456.webp" />
 * // Result: alt="Best Study Abroad Consultants"
 * 
 * @example
 * // Custom alt text
 * <SmartImage src="/api/uploads/image.webp" alt="Custom description" />
 * // Result: alt="Custom description"
 * 
 * @example
 * // Using title as alt
 * <SmartImage src="/api/uploads/image.webp" title="Image Title" />
 * // Result: alt="Image Title" title="Image Title"
 */
export function SmartImage({ src, alt, title, priority, disableResponsive, ...props }: SmartImageProps) {
  // Priority: alt prop > title prop > auto-generated from filename
  // If no alt is assigned, auto-detect the title from filename
  const autoGeneratedAlt = extractAltText(src);
  const finalAlt = alt || title || autoGeneratedAlt;
  
  // Use title if provided, otherwise use the auto-generated alt as title
  const finalTitle = title || autoGeneratedAlt;
  
  // Generate responsive srcset for uploaded images (not for attached_assets)
  const { srcSet, sizes } = useMemo(() => {
    // Skip responsive images if disabled or not an uploads URL
    if (disableResponsive || !src.includes('/api/uploads/')) {
      return { srcSet: undefined, sizes: undefined };
    }

    // Extract filename from /api/uploads/filename.ext
    const filename = src.split('/api/uploads/')[1];
    if (!filename) {
      return { srcSet: undefined, sizes: undefined };
    }

    // Generate srcset for mobile optimization
    const srcSet = [
      `/api/images/optimize/${filename}?w=320&q=75 320w`,
      `/api/images/optimize/${filename}?w=640&q=75 640w`,
      `/api/images/optimize/${filename}?w=960&q=80 960w`,
      `/api/images/optimize/${filename}?w=1280&q=80 1280w`,
      `${src} 1920w` // Original size
    ].join(', ');

    // Responsive sizes for better mobile performance
    const sizes = '(max-width: 640px) 320px, (max-width: 960px) 640px, (max-width: 1280px) 960px, 1280px';

    return { srcSet, sizes };
  }, [src, disableResponsive]);
  
  return (
    <img
      src={src}
      srcSet={srcSet}
      sizes={sizes}
      alt={finalAlt}
      title={finalTitle}
      loading={priority ? "eager" : "lazy"}
      {...(priority ? { fetchpriority: "high" } : {})}
      {...props}
    />
  );
}

export default SmartImage;
